### ISSUE TITLE
SSLError handshake_failure

### ISSUE THREAD

**Issue by oppianmatt** [jordansissel/ruby-ftw#31]
Been getting an SSLError recently all of a sudden with logstash trying to POST to hipchat. 

```
{:timestamp=>"2015-06-16T11:04:05.241000+0100", :message=>"Unhandled exception", :request=><FTW::Request(@4134) @protocol="https" @body="room_id=Warnings&from=logstash&color=yellow&notify=0&message=2015-06-16+10%3A03%3A36+UTC%3A+campsite+accessed+from+different+path" @method="POST" @headers=FTW::HTTP::Headers <{"host"=>"api.hipchat.com", "connection"=>"keep-alive", "content-type"=>"application/x-www-form-urlencoded", "content-length"=>129}> @version=1.1 @request_uri="/v1/rooms/message?auth_token=xxx" @logger=#<Cabin::Channel:0x64f221c7 @subscriber_lock=#<Mutex:0x5487c397>, @data={}, @metrics=#<Cabin::Metrics:0x1d3a19dc @channel=#<Cabin::Channel:0x64f221c7 ...>, @metrics={}, @metrics_lock=#<Mutex:0x5177c981>>, @subscribers={}, @level=:info> @port=443 >, :response=>nil, :exception=>#<OpenSSL::SSL::SSLError: Received fatal alert: handshake_failure>, :stacktrace=>["org/jruby/ext/openssl/SSLSocket.java:185:in `connect_nonblock'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/ftw-0.0.42/lib/ftw/connection.rb:399:in `do_secure'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/ftw-0.0.42/lib/ftw/connection.rb:379:in `secure'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/ftw-0.0.42/lib/ftw/agent.rb:449:in `connect'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/ftw-0.0.42/lib/ftw/agent.rb:283:in `execute'", "/opt/logstash/lib/logstash/outputs/hipchat.rb:61:in `receive'", "/opt/logstash/lib/logstash/outputs/base.rb:86:in `handle'", "(eval):609:in `initialize'", "org/jruby/RubyProc.java:271:in `call'", "/opt/logstash/lib/logstash/pipeline.rb:266:in `output'", "/opt/logstash/lib/logstash/pipeline.rb:225:in `outputworker'", "/opt/logstash/lib/logstash/pipeline.rb:152:in `start_outputs'"], :level=>:warn}
```

Ubuntu 12.04
OpenSSL up to date

Have even tried to install gem certified to fix but still the same issue.

```
env GEM_HOME=vendor/bundle/jruby/1.9 GEM_PATH="" java -jar vendor/jar/jruby-complete-1.7.17.jar -S gem install certified
```

**Comment by wscheele** [comment]
i have the same issue.
seems that somehow the hardcoded MOZILLA_MODERN cipher setup in combination with the other sslcontext settings leads to an inability to agree on a cipher during handshake with api.hipchat.com.

disabling the cipher override in connection.rb (line 363)
```
#sslcontext.ciphers = settings[:ciphers]
```
'fixes' this. it is still not entirely clear to me how to properly resolve this.
Starting logstash with "-Djavax.net.debug=ssl:handshake:verbose" shows that with settings[:ciphers] there are only 4 cipher options offered in the ClientHello as well as limited options.

**Comment by jordansissel** [comment]
@wscheele you can configure the SSL settings in FTW::Agent#configuration, though it's not well documented at this time.

**Comment by wscheele** [comment]
thanks @jordansissel . i guess in this case logstash would need to utilize that (i am not sure, but i guess i can't configure logstash to configure ftw). also: i didn't figure out the 'proper' configuration that would be needed. i could ofcourse simply print and utilize the working cipher settings, but wanted to first better understand what is going on, and where the problem lies.

would you then also argue this is not an ftw, but a logstash issue (hipchat + https outputs)?
the way the code is written (in the outputs and the ftw library) i was guessing that there is an assumption that it should 'just' work without changing the default configuration for this case.

**Comment by jordansissel** [comment]
@wscheele yeah I'm working on improving the http output to let you choose ciphers and also ssl version.

**Comment by wscheele** [comment]
ah i see. that would work. i am somewhat of a logstash newbie, where would you advice me to fix this until it is configurable?
i guess i could patch either the logstash hipchat/https output, or the ftw code until then.

**Comment by wscheele** [comment]
rephrasing my question somewhat: the ftw code seems to control the settings in order to force stricter security. what part of that do i loose by simply commenting out the cipher defaults dictated by ftw?

**Comment by jordansissel** [comment]
@wscheele nothing at this time, I should have a fix available later this week that you can install easily with Logstash 1.5.0 or later

**Comment by wscheele** [comment]
ok, i'll roll-out a temp patch on ftw until the fix (we are still running 1.4, so need to test 1.5 first anyway).
thanks for the feedback

**Comment by jespada** [comment]
@jordansissel do you have the patch somewhere? I run into the same problem, I can test it if you want :)

**Comment by jordansissel** [comment]
@jespada not at this time. I worked towards a solution, but there's bugs in JRuby that prevent this from being easily solved (IO::select on SSLSocket's doesn't work well under JRuby, and ftw requires this)

**Comment by zeki893** [comment]
Any updates to this? hipchat integration stopped working for over a month now. I was using 1.5.0 and I just updated to logstash-1.5.3 and it's still not working.

**Comment by jordansissel** [comment]
Logstash's http output is moving to use manticore as the library instead of ftw which should help. I don't have any ETA on that work, however.

**Comment by swsachith** [comment]
Any documentation on how I can use SSL with the FTW:Agent ? to support https?

**Comment by windhamdamon** [comment]
I hit this recently and tried to disable the cipher override as wscheele mentioned earlier but now OpenSSL is complaining about certificate verification, even though the cert is root-signed by a CA that is in Java's "cacerts" file.  Here's the error:

:exception=>#<OpenSSL::SSL::SSLError: certificate verify failed>, :stacktrace=>["org/jruby/ext/openssl/SSLSocket.java:195:in `connect_nonblock'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/ftw-0.0.44/lib/ftw/connection.rb:413:in `do_secure'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/ftw-0.0.44/lib/ftw/connection.rb:393:in `secure'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/ftw-0.0.44/lib/ftw/agent.rb:449:in `connect'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/ftw-0.0.44/lib/ftw/agent.rb:283:in `execute'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-http-1.0.0/lib/logstash/outputs/http.rb:126:in `receive'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/outputs/base.rb:88:in `handle'", "(eval):22:in `output_func'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/pipeline.rb:244:in `outputworker'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/pipeline.rb:166:in `start_outputs'

Turning on verbose debugging for SSL, I see the following:

trustStore is: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.51-1.b16.6.amzn1.x86_64/jre/lib/security/cacerts
trustStore type is : jks
trustStore provider is : 
init truststore

[Abbreviated]

Untrusted certificate found; here's what I know:
  Why it's untrusted: (20) unable to get local issuer certificate
  Missing cert for issuer: /C=US/O=GeoTrust Inc./OU=(c) 2008 GeoTrust Inc. - For authorized use only/CN=GeoTrust Primary Certification Authority - G3
  Issuer hash: -381d59c8
Trust? [(N)o/(Y)es/(P)ersistent] stty: standard input: Inappropriate ioctl for device

However, GeoTrust's CA cert is present:

[root]# keytool -list -v -keystore /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.51-1.b16.6.amzn1.x86_64/jre/lib/security/cacerts |grep -i "GeoTrust Primary Certification Authority - G3"
Enter keystore password:  changeit
Owner: CN=GeoTrust Primary Certification Authority - G3, OU=(c) 2008 GeoTrust Inc. - For authorized use only, O=GeoTrust Inc., C=US
Issuer: CN=GeoTrust Primary Certification Authority - G3, OU=(c) 2008 GeoTrust Inc. - For authorized use only, O=GeoTrust Inc., C=US

Any idea how I can get past this?

Thanks,

Damon

**Comment by mscharley** [comment]
Any updates on this?

**Comment by mindscratch** [comment]
I believe logstash 2 is now using manticore.

**Comment by ruggione** [comment]
Hi @windhamdamon,
i have the same error. You have news?
Thanks
Michele
